apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

## To change the newTag just run: kustomize edit set image vitor96k/arithmetic-backend:4.0.0
images:
- name: vitor96k/arithmetic-backend
  newTag: 1.0.0
