apiVersion: v1
kind: Service
metadata:
  name: arithmetic-backend-cluster-ip-service
spec:
  selector:
    app: arithmetic-backend
  type: ClusterIP

  ports:
  - port: 80 # Service Port
    targetPort: 7001 # Container Port
    protocol: TCP
